
#include <Arduino.h>
#include <AudioStream.h>
#include "sample_value.h"

const int16_t zeros[AUDIO_BLOCK_SAMPLES] = { 0 };
#define ONE_VALUE ((int16_t)0x8000)
const int16_t ones[AUDIO_BLOCK_SAMPLES] = {
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
#if AUDIO_BLOCK_SAMPLES > 8
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
#if AUDIO_BLOCK_SAMPLES > 16
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
#if AUDIO_BLOCK_SAMPLES > 32
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
#if AUDIO_BLOCK_SAMPLES > 64
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
  ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE, ONE_VALUE,
#endif
#endif
#endif
#endif
};
#undef ONE_VALUE
